<a href="https://colab.research.google.com/github/juyeon-shin/PROJECT/blob/main/2021/CJ%EB%8C%80%ED%95%9C%ED%86%B5%EC%9A%B4%20%EB%AF%B8%EB%9E%98%EA%B8%B0%EC%88%A0%20%EC%B1%8C%EB%A6%B0%EC%A7%80%20AI%C2%B7%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EA%B2%BD%EC%A7%84%EB%8C%80%ED%9A%8C/02.%20%EC%A3%BC%EC%86%8C%EC%A0%84%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 데이터 & 모듈

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

KeyboardInterrupt: ignored

In [ ]:
import io
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly
import warnings
warnings.filterwarnings('ignore')

### FC3 : 송화인 주소 & 수화인주소1 전처리

In [ ]:
fc3 = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/2021년 미래기술 챌린지_211005/1. 이커머스 FC주문 데이터/1-1. 이커머스 FC주문 데이터_3월(전처리).csv')
fc3

In [ ]:
fc3.groupby(['송화인주소1']).count()

In [ ]:
for i in range(len(fc3)):
  if fc3['송화인주소1'][i] == '경기':
    fc3['송화인주소1'][i] = '경기도'

fc3.groupby(['송화인주소1']).count()

In [ ]:
fc3.groupby(['수화인주소1']).count()

In [ ]:
for i in range(len(fc3)):
  if  fc3['수화인주소1'][i] == '경기':
    fc3['수화인주소1'][i] = '경기도'
  elif fc3['수화인주소1'][i] == '\t경기도':
    fc3['수화인주소1'][i] = '경기도'
  elif fc3['수화인주소1'][i] == '서울시' :
    fc3['수화인주소1'][i] = '서울특별시'
  elif fc3['수화인주소1'][i] == '서울' :
    fc3['수화인주소1'][i] = '서울특별시'
  elif fc3['수화인주소1'][i] == '인천' :
    fc3['수화인주소1'][i] = '인천광역시'
  elif fc3['수화인주소1'][i] == '인천시' :
    fc3['수화인주소1'][i] = '인천광역시'
  elif fc3['수화인주소1'][i] == '경남':
    fc3['수화인주소1'][i] = '경상남도'
  elif fc3['수화인주소1'][i] == '경북':
    fc3['수화인주소1'][i] = '경상북도'
  elif fc3['수화인주소1'][i] == '강원':
    fc3['수화인주소1'][i] = '강원도'
  elif fc3['수화인주소1'][i] == '광주':
    fc3['수화인주소1'][i] = '광주광역시'
  elif fc3['수화인주소1'][i] == '대구' :
    fc3['수화인주소1'][i] = '대구광역시'
  elif fc3['수화인주소1'][i] == '대구시' :
    fc3['수화인주소1'][i] = '대구광역시'
  elif fc3['수화인주소1'][i] == '대전':
    fc3['수화인주소1'][i] = '대전광역시'
  elif fc3['수화인주소1'][i] == '부산':
    fc3['수화인주소1'][i] = '부산광역시'
  elif fc3['수화인주소1'][i] == '부산시' :
    fc3['수화인주소1'][i] = '부산광역시'
  elif fc3['수화인주소1'][i] == '세종':
    fc3['수화인주소1'][i] = '세종특별자치시'
  elif fc3['수화인주소1'][i] == '울산':
    fc3['수화인주소1'][i] = '울산광역시'
  elif fc3['수화인주소1'][i] == '전남':
    fc3['수화인주소1'][i] = '전라남도'
  elif fc3['수화인주소1'][i] == '전북':
    fc3['수화인주소1'][i] = '전라북도'
  elif fc3['수화인주소1'][i] == '제주':
    fc3['수화인주소1'][i] = '제주특별자치도'
  elif fc3['수화인주소1'][i] == '충남':
    fc3['수화인주소1'][i] = '충청남도'
  elif fc3['수화인주소1'][i] == '충북':
    fc3['수화인주소1'][i] = '충청북도'
  
  

fc3.groupby(['수화인주소1']).count()

In [ ]:
want_del = fc3[fc3['수화인주소1'] == '강서구'].index
fc3 = fc3.drop(want_del)
want_del = fc3[fc3['수화인주소1'] == '경기도수원시'].index
fc3 = fc3.drop(want_del)
want_del = fc3[fc3['수화인주소1'] == '청주시'].index
fc3 = fc3.drop(want_del)

fc3.groupby(['수화인주소1']).count()

### FC4 : 송화인주소1 수화인주소 전처리

In [ ]:
fc4 = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/2021년 미래기술 챌린지_211005/1. 이커머스 FC주문 데이터/1-2. 이커머스 FC주문 데이터_4월(전처리).csv')

In [ ]:
fc4.groupby(['송화인주소1']).count()

In [ ]:
for i in range(len(fc4)):
  if fc4['송화인주소1'][i] == '경기':
    fc4['송화인주소1'][i] = '경기도'

fc4.groupby(['송화인주소1']).count()

In [ ]:
fc4.groupby(['수화인주소1']).count()

In [ ]:
for i in range(len(fc4)):
  if  fc4['수화인주소1'][i] == '경기':
    fc4['수화인주소1'][i] = '경기도'
  elif fc4['수화인주소1'][i] == '\t경기도':
    fc4['수화인주소1'][i] = '경기도'
  elif fc4['수화인주소1'][i] == '서울시' :
    fc4['수화인주소1'][i] = '서울특별시'
  elif fc4['수화인주소1'][i] == '서울' :
    fc4['수화인주소1'][i] = '서울특별시'
  elif fc4['수화인주소1'][i] == '인천' :
    fc4['수화인주소1'][i] = '인천광역시'
  elif fc4['수화인주소1'][i] == '인천시' :
    fc4['수화인주소1'][i] = '인천광역시'
  elif fc4['수화인주소1'][i] == '경남':
    fc4['수화인주소1'][i] = '경상남도'
  elif fc4['수화인주소1'][i] == '경북':
    fc4['수화인주소1'][i] = '경상북도'
  elif fc4['수화인주소1'][i] == '강원':
    fc4['수화인주소1'][i] = '강원도'
  elif fc4['수화인주소1'][i] == '광주':
    fc4['수화인주소1'][i] = '광주광역시'
  elif fc4['수화인주소1'][i] == '대구' :
    fc4['수화인주소1'][i] = '대구광역시'
  elif fc4['수화인주소1'][i] == '대구시' :
    fc4['수화인주소1'][i] = '대구광역시'
  elif fc4['수화인주소1'][i] == '대전':
    fc4['수화인주소1'][i] = '대전광역시'
  elif fc4['수화인주소1'][i] == '부산':
    fc4['수화인주소1'][i] = '부산광역시'
  elif fc4['수화인주소1'][i] == '부산시' :
    fc4['수화인주소1'][i] = '부산광역시'
  elif fc4['수화인주소1'][i] == '세종':
    fc4['수화인주소1'][i] = '세종특별자치시'
  elif fc4['수화인주소1'][i] == '세종시':
    fc4['수화인주소1'][i] = '세종특별자치시'
  elif fc4['수화인주소1'][i] == '울산':
    fc4['수화인주소1'][i] = '울산광역시'
  elif fc4['수화인주소1'][i] == '전남':
    fc4['수화인주소1'][i] = '전라남도'
  elif fc4['수화인주소1'][i] == '전북':
    fc4['수화인주소1'][i] = '전라북도'
  elif fc4['수화인주소1'][i] == '제주':
    fc4['수화인주소1'][i] = '제주특별자치도'
  elif fc4['수화인주소1'][i] == '충남':
    fc4['수화인주소1'][i] = '충청남도'
  elif fc4['수화인주소1'][i] == '충북':
    fc4['수화인주소1'][i] = '충청북도'
  
  

fc4.groupby(['수화인주소1']).count()

In [ ]:
want_del = fc4[fc4['수화인주소1'] == '경기도수원시'].index
fc4 = fc4.drop(want_del)
want_del = fc4[fc4['수화인주소1'] == '마포구'].index
fc4 = fc4.drop(want_del)
want_del = fc4[fc4['수화인주소1'] == '영등포구'].index
fc4 = fc4.drop(want_del)
want_del = fc4[fc4['수화인주소1'] == '전남목포시'].index
fc4 = fc4.drop(want_del)
want_del = fc4[fc4['수화인주소1'] == '충남금산군'].index
fc4 = fc4.drop(want_del)

fc4.groupby(['수화인주소1']).count()

### FC5 : 송화인주소1 수화인주소 전처리

In [ ]:
fc5 = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/2021년 미래기술 챌린지_211005/1. 이커머스 FC주문 데이터/1-3. 이커머스 FC주문 데이터_5월(전처리).csv')

In [ ]:
fc5.groupby(['송화인주소1']).count()

           창고코드  고객주문번호  대한통운주문번호    주문유형  ...  배송처별주문분할여부  송화인주소2  수화인주소1  수화인주소2
송화인주소1                                     ...
경기         8549    8549      8549    8549  ...        8549    8549    8549     814
경기도      436537  436537    436535  436537  ...      436537  436420  436537  435910
경상북도          6       6         6       6  ...           6       0       6       6
대전광역시        18      18        18      18  ...          18       0      18      18
서울시        1311    1311      1311    1311  ...        1311    1311    1311       0
서울특별시       721     721       721     721  ...         721     721     721     721
세종특별자치시     324     324       324     324  ...         324       0     324     324
인천광역시       339     339       339     339  ...         339       0     339     339
충청남도       2529    2529      2529    2529  ...        2529    2529    2529    2528
충청북도         17      17        17      17  ...          17      17      17      17

[10 rows x 31 columns]

In [ ]:
for i in range(len(fc5)):
  if fc5['송화인주소1'][i] == '경기':
    fc5['송화인주소1'][i] = '경기도'

fc5.groupby(['송화인주소1']).count()

           창고코드  고객주문번호  대한통운주문번호    주문유형  ...  배송처별주문분할여부  송화인주소2  수화인주소1  수화인주소2
송화인주소1                                     ...
경기도      445086  445086    445084  445086  ...      445086  444969  445086  436724
경상북도          6       6         6       6  ...           6       0       6       6
대전광역시        18      18        18      18  ...          18       0      18      18
서울시        1311    1311      1311    1311  ...        1311    1311    1311       0
서울특별시       721     721       721     721  ...         721     721     721     721
세종특별자치시     324     324       324     324  ...         324       0     324     324
인천광역시       339     339       339     339  ...         339       0     339     339
충청남도       2529    2529      2529    2529  ...        2529    2529    2529    2528
충청북도         17      17        17      17  ...          17      17      17      17

[9 rows x 31 columns]

In [ ]:
fc5.groupby(['수화인주소1']).count()

                    창고코드  고객주문번호  대한통운주문번호  ...  송화인주소1  송화인주소2  수화인주소2
수화인주소1                                      ...
(12730)                2       2         2  ...       2       2       0
강원                    92      92        92  ...      92      92      80
강원도                13337   13337     13337  ...   13337   13311   13059
경기                   815     815       815  ...     815     814     723
경기도               124317  124317    124317  ...  124317  124094  121746
경남                   194     194       194  ...     194     194     175
경북                   171     171       171  ...     171     171     151
경상남도               28152   28152     28152  ...   28152   28098   27575
경상북도               20491   20491     20491  ...   20491   20455   20063
광주                    63      63        63  ...      63      62      59
광주광역시              11915   11915     11915  ...   11915   11891   11633
대구                   165     165       165  ...     165     165     151
대구광역시              18859   18859     18859  ...   18859   18825   18369
대전                   111     111       111  ...     111     111     102
대전광역시              12035   12035     12035  ...   12035   12015   11838
부산                   226     226       226  ...     226     224     207
부산광역시              27079   27079     27079  ...   27079   27036   26508
부산시                    1       1         1  ...       1       1       1
상주시                    1       1         1  ...       1       1       0
서울                   758     758       758  ...     758     758     669
서울시                   13      13        13  ...      13      13       4
서울특별시              94166   94166     94165  ...   94166   93989   92310
세종                     1       1         1  ...       1       1       0
세종특별자치시             3943    3943      3943  ...    3943    3939    3824
울산                    84      84        84  ...      84      84      77
울산광역시               8779    8779      8779  ...    8779    8765    8616
인천                   174     174       174  ...     174     174     159
인천광역시              23302   23302     23302  ...   23302   23267   22806
인천광역시 서구 정서진로 47       7       7         7  ...       7       7       0
인천시                    2       2         2  ...       2       2       1
전남                   112     112       112  ...     112     112      96
전라남도               13727   13727     13726  ...   13727   13699   13427
전라북도               12526   12526     12526  ...   12526   12509   12263
전북                   110     110       110  ...     110     110     101
제주                    14      14        14  ...      14      14      11
제주특별자치도             2733    2733      2733  ...    2733    2727    2651
중구                     2       2         2  ...       2       2       0
청남도                    3       3         3  ...       3       3       0
충남                   112     112       112  ...     112     112     100
충북                    52      52        52  ...      52      52      50
충청남도               18379   18379     18379  ...   18379   18352   17998
충청북도               13323   13323     13323  ...   13323   13291   13074
평택시                    3       3         3  ...       3       3       0

[43 rows x 31 columns]

In [ ]:
for i in range(len(fc5)):
  if  fc5['수화인주소1'][i] == '경기':
    fc5['수화인주소1'][i] = '경기도'
  elif fc5['수화인주소1'][i] == '\t경기도':
    fc5['수화인주소1'][i] = '경기도'
  elif fc5['수화인주소1'][i] == '서울시' :
    fc5['수화인주소1'][i] = '서울특별시'
  elif fc5['수화인주소1'][i] == '서울' :
    fc5['수화인주소1'][i] = '서울특별시'
  elif fc5['수화인주소1'][i] == '인천' :
    fc5['수화인주소1'][i] = '인천광역시'
  elif fc5['수화인주소1'][i] == '인천시' :
    fc5['수화인주소1'][i] = '인천광역시'
  elif fc5['수화인주소1'][i] == '경남':
    fc5['수화인주소1'][i] = '경상남도'
  elif fc5['수화인주소1'][i] == '경북':
    fc5['수화인주소1'][i] = '경상북도'
  elif fc5['수화인주소1'][i] == '강원':
    fc5['수화인주소1'][i] = '강원도'
  elif fc5['수화인주소1'][i] == '광주':
    fc5['수화인주소1'][i] = '광주광역시'
  elif fc5['수화인주소1'][i] == '대구' :
    fc5['수화인주소1'][i] = '대구광역시'
  elif fc5['수화인주소1'][i] == '대구시' :
    fc5['수화인주소1'][i] = '대구광역시'
  elif fc5['수화인주소1'][i] == '대전':
    fc5['수화인주소1'][i] = '대전광역시'
  elif fc5['수화인주소1'][i] == '부산':
    fc5['수화인주소1'][i] = '부산광역시'
  elif fc5['수화인주소1'][i] == '부산시' :
    fc5['수화인주소1'][i] = '부산광역시'
  elif fc5['수화인주소1'][i] == '세종':
    fc5['수화인주소1'][i] = '세종특별자치시'
  elif fc5['수화인주소1'][i] == '세종시':
    fc5['수화인주소1'][i] = '세종특별자치시'
  elif fc5['수화인주소1'][i] == '울산':
    fc5['수화인주소1'][i] = '울산광역시'
  elif fc5['수화인주소1'][i] == '전남':
    fc5['수화인주소1'][i] = '전라남도'
  elif fc5['수화인주소1'][i] == '전북':
    fc5['수화인주소1'][i] = '전라북도'
  elif fc5['수화인주소1'][i] == '제주':
    fc5['수화인주소1'][i] = '제주특별자치도'
  elif fc5['수화인주소1'][i] == '충남':
    fc5['수화인주소1'][i] = '충청남도'
  elif fc5['수화인주소1'][i] == '충북':
    fc5['수화인주소1'][i] = '충청북도'
  
  

fc5.groupby(['수화인주소1']).count()

                    창고코드  고객주문번호  대한통운주문번호  ...  송화인주소1  송화인주소2  수화인주소2
수화인주소1                                      ...
(12730)                2       2         2  ...       2       2       0
강원도                13429   13429     13429  ...   13429   13403   13139
경기도               125132  125132    125132  ...  125132  124908  122469
경상남도               28346   28346     28346  ...   28346   28292   27750
경상북도               20662   20662     20662  ...   20662   20626   20214
광주광역시              11978   11978     11978  ...   11978   11953   11692
대구광역시              19024   19024     19024  ...   19024   18990   18520
대전광역시              12146   12146     12146  ...   12146   12126   11940
부산광역시              27306   27306     27306  ...   27306   27261   26716
상주시                    1       1         1  ...       1       1       0
서울특별시              94937   94937     94936  ...   94937   94760   92983
세종특별자치시             3944    3944      3944  ...    3944    3940    3824
울산광역시               8863    8863      8863  ...    8863    8849    8693
인천광역시              23478   23478     23478  ...   23478   23443   22966
인천광역시 서구 정서진로 47       7       7         7  ...       7       7       0
전라남도               13839   13839     13838  ...   13839   13811   13523
전라북도               12636   12636     12636  ...   12636   12619   12364
제주특별자치도             2747    2747      2747  ...    2747    2741    2662
중구                     2       2         2  ...       2       2       0
청남도                    3       3         3  ...       3       3       0
충청남도               18491   18491     18491  ...   18491   18464   18098
충청북도               13375   13375     13375  ...   13375   13343   13124
평택시                    3       3         3  ...       3       3       0

[23 rows x 31 columns]

In [ ]:
want_del = fc5[fc5['수화인주소1'] == '(12730)'].index
fc5 = fc5.drop(want_del)
want_del = fc5[fc5['수화인주소1'] == '상주시'].index
fc5 = fc5.drop(want_del)
want_del = fc5[fc5['수화인주소1'] == '인천광역시 서구 정서진로 47'].index
fc5 = fc5.drop(want_del)
want_del = fc5[fc5['수화인주소1'] == '중구'].index
fc5 = fc5.drop(want_del)
want_del = fc5[fc5['수화인주소1'] == '청남도'].index
fc5 = fc5.drop(want_del)
want_del = fc5[fc5['수화인주소1'] == '평택시'].index
fc5 = fc5.drop(want_del)

fc5.groupby(['수화인주소1']).count()

                    창고코드  고객주문번호  대한통운주문번호  ...  송화인주소1  송화인주소2  수화인주소2
수화인주소1                                      ...
강원도                13429   13429     13429  ...   13429   13403   13139
경기도               125132  125132    125132  ...  125132  124908  122469
경상남도               28346   28346     28346  ...   28346   28292   27750
경상북도               20662   20662     20662  ...   20662   20626   20214
광주광역시              11978   11978     11978  ...   11978   11953   11692
대구광역시              19024   19024     19024  ...   19024   18990   18520
대전광역시              12146   12146     12146  ...   12146   12126   11940
부산광역시              27306   27306     27306  ...   27306   27261   26716
서울특별시              94937   94937     94936  ...   94937   94760   92983
세종특별자치시             3944    3944      3944  ...    3944    3940    3824
울산광역시               8863    8863      8863  ...    8863    8849    8693
인천광역시              23478   23478     23478  ...   23478   23443   22966
인천광역시 서구 정서진로 47       7       7         7  ...       7       7       0
전라남도               13839   13839     13838  ...   13839   13811   13523
전라북도               12636   12636     12636  ...   12636   12619   12364
제주특별자치도             2747    2747      2747  ...    2747    2741    2662
충청남도               18491   18491     18491  ...   18491   18464   18098
충청북도               13375   13375     13375  ...   13375   13343   13124

[18 rows x 31 columns]

### FC6 : 송화인주소1 수화인주소 전처리

In [ ]:
fc6 = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/2021년 미래기술 챌린지_211005/1. 이커머스 FC주문 데이터/1-4. 이커머스 FC주문 데이터_6월(전처리).csv')

In [ ]:
fc6.groupby(['송화인주소1']).count()

           창고코드  고객주문번호  대한통운주문번호    주문유형  ...  배송처별주문분할여부  송화인주소2  수화인주소1  수화인주소2
송화인주소1                                     ...
경기        14209   14209     14209   14209  ...       14209   14209   14205    2814
경기도      618991  618991    618988  618991  ...      618991  557574  618990  618838
서울시         209     209       209     209  ...         209     209     209       0
서울특별시      1062    1062      1062    1062  ...        1062    1062    1062    1062
세종특별자치시   25306   25306     25306   25306  ...       25306       0   25306   25305
인천광역시       299     299       299     299  ...         299       0     299     299
충청남도      16235   16235     16235   16235  ...       16235   16235   16234   16234

[7 rows x 31 columns]

In [ ]:
for i in range(len(fc6)):
  if fc6['송화인주소1'][i] == '경기':
    fc6['송화인주소1'][i] = '경기도'

fc6.groupby(['송화인주소1']).count()

           창고코드  고객주문번호  대한통운주문번호    주문유형  ...  배송처별주문분할여부  송화인주소2  수화인주소1  수화인주소2
송화인주소1                                     ...
경기도      633200  633200    633197  633200  ...      633200  571783  633195  621652
서울시         209     209       209     209  ...         209     209     209       0
서울특별시      1062    1062      1062    1062  ...        1062    1062    1062    1062
세종특별자치시   25306   25306     25306   25306  ...       25306       0   25306   25305
인천광역시       299     299       299     299  ...         299       0     299     299
충청남도      16235   16235     16235   16235  ...       16235   16235   16234   16234

[6 rows x 31 columns]

In [ ]:
fc6.groupby(['수화인주소1']).count()

                              창고코드  고객주문번호  대한통운주문번호  ...  송화인주소1  송화인주소2  수화인주소2
수화인주소1                                                ...
(13279)                          1       1         1  ...       1       1       0
(13499)                          1       1         1  ...       1       1       0
(14782)                          1       1         1  ...       1       1       0
(22738)                          1       1         1  ...       1       1       0
(30100)                          1       1         1  ...       1       1       0
(53298)                          2       2         2  ...       2       2       0
[16817]                          1       1         1  ...       1       1       1
道路名稱首爾特別市中區麻將路1街22號（STUDIO       1       1         1  ...       1       1       0
강원                              83      83        83  ...      83      69      80
강원도                          19702   19702     19702  ...   19702   17319   19437
경기                            1036    1036      1036  ...    1036     928     999
경기도                         189403  189403    189402  ...  189403  165007  186025
경기도시흥시                           4       4         4  ...       4       4       4
경남                             213     213       213  ...     213     194     199
경북                             198     198       198  ...     198     176     188
경삼남도                             1       1         1  ...       1       1       0
경상남도                         41215   41215     41215  ...   41215   35608   40522
경상북도                         29953   29953     29953  ...   29953   26040   29430
광주                             123     123       123  ...     123     109     121
광주광역시                        17726   17726     17726  ...   17726   15321   17457
대구                             190     190       190  ...     190     164     185
대구광역시                        28967   28967     28967  ...   28967   25048   28456
대구시                              1       1         1  ...       1       1       1
대전                             113     113       113  ...     113     103     111
대전광역시                        17869   17869     17869  ...   17869   15571   17524
부산                             260     260       260  ...     260     228     252
부산광역시                        41272   41272     41271  ...   41272   35825   40541
서울                             840     840       840  ...     840     756     816
서울시                             25      25        25  ...      25      25       3
서울특별시                       141894  141894    141894  ...  141894  124502  139577
세종                               1       1         1  ...       1       1       0
세종특별자치시                       6109    6109      6109  ...    6109    5191    5950
영천시                              1       1         1  ...       1       1       1
울산                              83      83        83  ...      83      69      80
울산광역시                        12625   12625     12625  ...   12625   10865   12354
울특별시                             1       1         1  ...       1       1       0
인천                             207     207       207  ...     207     185     202
인천광역시                        35623   35623     35623  ...   35623   31119   34996
인천광역시미추홀구                        1       1         1  ...       1       1       1
인천시                              2       2         2  ...       2       2       0
전남                              97      97        97  ...      97      85      94
전남목포시                            1       1         1  ...       1       1       0
전라남도                         20321   20321     20320  ...   20321   17759   20025
전라북도                         18939   18939     18939  ...   18939   16572   18611
전북                             148     148       148  ...     148     124     143
제주                              11      11        11  ...      11       8      10
제주특별자치도                       4349    4349      4349  ...    4349    3595    4236
충남                             134     134       134  ...     134     116     126
충북                              76      76        76  ...      76      73      72
충청남도                         26639   26639     26639  ...   26639   23139   26243
충청북도                         19836   19836     19836  ...   19836   17364   19474
태종로711번길                         1       1         1  ...       1       1       1
화성시                              3       3         3  ...       3       3       0

[53 rows x 31 columns]

In [ ]:
for i in range(len(fc6)):
  if  fc6['수화인주소1'][i] == '경기':
    fc6['수화인주소1'][i] = '경기도'
  elif fc6['수화인주소1'][i] == '\t경기도':
    fc6['수화인주소1'][i] = '경기도'
  elif fc6['수화인주소1'][i] == '서울시' :
    fc6['수화인주소1'][i] = '서울특별시'
  elif fc6['수화인주소1'][i] == '서울' :
    fc6['수화인주소1'][i] = '서울특별시'
  elif fc6['수화인주소1'][i] == '인천' :
    fc6['수화인주소1'][i] = '인천광역시'
  elif fc6['수화인주소1'][i] == '인천시' :
    fc6['수화인주소1'][i] = '인천광역시'
  elif fc6['수화인주소1'][i] == '경남':
    fc6['수화인주소1'][i] = '경상남도'
  elif fc6['수화인주소1'][i] == '경북':
    fc6['수화인주소1'][i] = '경상북도'
  elif fc6['수화인주소1'][i] == '강원':
    fc6['수화인주소1'][i] = '강원도'
  elif fc6['수화인주소1'][i] == '광주':
    fc6['수화인주소1'][i] = '광주광역시'
  elif fc6['수화인주소1'][i] == '대구' :
    fc6['수화인주소1'][i] = '대구광역시'
  elif fc6['수화인주소1'][i] == '대구시' :
    fc6['수화인주소1'][i] = '대구광역시'
  elif fc6['수화인주소1'][i] == '대전':
    fc6['수화인주소1'][i] = '대전광역시'
  elif fc6['수화인주소1'][i] == '부산':
    fc6['수화인주소1'][i] = '부산광역시'
  elif fc6['수화인주소1'][i] == '부산시' :
    fc6['수화인주소1'][i] = '부산광역시'
  elif fc6['수화인주소1'][i] == '세종':
    fc6['수화인주소1'][i] = '세종특별자치시'
  elif fc6['수화인주소1'][i] == '세종시':
    fc6['수화인주소1'][i] = '세종특별자치시'
  elif fc6['수화인주소1'][i] == '울산':
    fc6['수화인주소1'][i] = '울산광역시'
  elif fc6['수화인주소1'][i] == '전남':
    fc6['수화인주소1'][i] = '전라남도'
  elif fc6['수화인주소1'][i] == '전북':
    fc6['수화인주소1'][i] = '전라북도'
  elif fc6['수화인주소1'][i] == '제주':
    fc6['수화인주소1'][i] = '제주특별자치도'
  elif fc6['수화인주소1'][i] == '충남':
    fc6['수화인주소1'][i] = '충청남도'
  elif fc6['수화인주소1'][i] == '충북':
    fc6['수화인주소1'][i] = '충청북도'
  
  

fc6.groupby(['수화인주소1']).count()

                              창고코드  고객주문번호  대한통운주문번호  ...  송화인주소1  송화인주소2  수화인주소2
수화인주소1                                                ...
(13279)                          1       1         1  ...       1       1       0
(13499)                          1       1         1  ...       1       1       0
(14782)                          1       1         1  ...       1       1       0
(22738)                          1       1         1  ...       1       1       0
(30100)                          1       1         1  ...       1       1       0
(53298)                          2       2         2  ...       2       2       0
[16817]                          1       1         1  ...       1       1       1
道路名稱首爾特別市中區麻將路1街22號（STUDIO       1       1         1  ...       1       1       0
강원도                          19785   19785     19785  ...   19785   17388   19517
경기도                         190439  190439    190438  ...  190439  165935  187024
경기도시흥시                           4       4         4  ...       4       4       4
경삼남도                             1       1         1  ...       1       1       0
경상남도                         41428   41428     41428  ...   41428   35802   40721
경상북도                         30151   30151     30151  ...   30151   26216   29618
광주광역시                        17849   17849     17849  ...   17849   15430   17578
대구광역시                        29158   29158     29158  ...   29158   25213   28642
대전광역시                        17982   17982     17982  ...   17982   15674   17635
부산광역시                        41532   41532     41531  ...   41532   36053   40793
서울특별시                       142759  142759    142759  ...  142759  125283  140396
세종특별자치시                       6110    6110      6110  ...    6110    5192    5950
영천시                              1       1         1  ...       1       1       1
울산광역시                        12708   12708     12708  ...   12708   10934   12434
울특별시                             1       1         1  ...       1       1       0
인천광역시                        35832   35832     35832  ...   35832   31306   35198
인천광역시미추홀구                        1       1         1  ...       1       1       1
전남목포시                            1       1         1  ...       1       1       0
전라남도                         20418   20418     20417  ...   20418   17844   20119
전라북도                         19087   19087     19087  ...   19087   16696   18754
제주특별자치도                       4360    4360      4360  ...    4360    3603    4246
충청남도                         26773   26773     26773  ...   26773   23255   26369
충청북도                         19912   19912     19912  ...   19912   17437   19546
태종로711번길                         1       1         1  ...       1       1       1
화성시                              3       3         3  ...       3       3       0

[33 rows x 31 columns]

In [ ]:
want_del = fc6[fc6['수화인주소1'] == '(13279)'].index
fc6 = fc6.drop(want_del)
want_del = fc6[fc6['수화인주소1'] == '(13499)'].index
fc6 = fc6.drop(want_del)
want_del = fc6[fc6['수화인주소1'] == '(14782)'].index
fc6 = fc6.drop(want_del)
want_del = fc6[fc6['수화인주소1'] == '(22738)'].index
fc6 = fc6.drop(want_del)
want_del = fc6[fc6['수화인주소1'] == '(30100)'].index
fc6 = fc6.drop(want_del)
want_del = fc6[fc6['수화인주소1'] == '(53298)'].index
fc6 = fc6.drop(want_del)
want_del = fc6[fc6['수화인주소1'] == '[16817]'].index
fc6 = fc6.drop(want_del)
want_del = fc6[fc6['수화인주소1'] == '道路名稱首爾特別市中區麻將路1街22號（STUDIO'].index
fc6 = fc6.drop(want_del)
want_del = fc6[fc6['수화인주소1'] == '경기도시흥시'].index
fc6 = fc6.drop(want_del)
want_del = fc6[fc6['수화인주소1'] == '경삼남도'].index
fc6 = fc6.drop(want_del)
want_del = fc6[fc6['수화인주소1'] == '울특별시'].index
fc6 = fc6.drop(want_del)
want_del = fc6[fc6['수화인주소1'] == '인천광역시미추홀구'].index
fc6 = fc6.drop(want_del)
want_del = fc6[fc6['수화인주소1'] == '전남목포시'].index
fc6 = fc6.drop(want_del)
want_del = fc6[fc6['수화인주소1'] == '태종로711번길'].index
fc6 = fc6.drop(want_del)
want_del = fc6[fc6['수화인주소1'] == '화성시'].index
fc6 = fc6.drop(want_del)

fc6.groupby(['수화인주소1']).count()

### 파일 저장

In [ ]:
fc3.to_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/2021년 미래기술 챌린지_211005/1. 이커머스 FC주문 데이터/1-1. 이커머스 FC주문 데이터_3월(전처리).csv', index=False)
fc4.to_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/2021년 미래기술 챌린지_211005/1. 이커머스 FC주문 데이터/1-2. 이커머스 FC주문 데이터_4월(전처리).csv', index=False)
fc5.to_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/2021년 미래기술 챌린지_211005/1. 이커머스 FC주문 데이터/1-3. 이커머스 FC주문 데이터_5월(전처리).csv', index=False)
fc6.to_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/2021년 미래기술 챌린지_211005/1. 이커머스 FC주문 데이터/1-4. 이커머스 FC주문 데이터_6월(전처리).csv', index=False)