## 2. 외부변수 전처리

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import io
import pandas as pd
import numpy as np
import datetime as dt
import plotly.express as px
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import seaborn as sns
import plotly
import warnings
warnings.filterwarnings('ignore')

### 2.1 날씨 데이터 전처리

In [ ]:
rain = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/날씨 data/202103_06 서울강수.csv',encoding='cp949', skiprows=7)
temp = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/날씨 data/202103_06 서울기온.csv',encoding='cp949', skiprows=7)

temp['강수량(mm)'] = rain['강수량(mm)']
temp = temp.fillna(0)
temp = temp.drop(['지점'], axis = 1)
temp

In [ ]:
temp['날짜'] = pd.to_datetime(temp['날짜'], format='%Y-%m-%d', errors='raise')
days = ['월','화','수','목','금','토','일']
temp['요일'] = temp['날짜'].dt.weekday

for i in range(len(temp)):
  temp['요일'][i] = days[temp['요일'][i]]

temp.columns = ['날짜','평균기온','최저기온','최고기온','강수량','요일']
temp['날짜'] = temp['날짜'].astype(str)
temp

In [ ]:
temp.to_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/날씨 data/202103_06 서울날씨.csv',index=False)

### 2.2 도 데이터 생성

In [ ]:
center_city0 = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/회귀분석용 data/center_city0.csv')
center_city1 = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/회귀분석용 data/center_city1.csv')
center_city2 = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/회귀분석용 data/center_city2.csv')
center_city3 = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/회귀분석용 data/center_city3.csv')
center_city4 = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/회귀분석용 data/center_city4.csv')
center_city6 = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/회귀분석용 data/center_city6.csv')

### 2.2.1 경기도 데이터셋 생성

In [ ]:
Gyeonggi = pd.concat([center_city0,center_city1,center_city2,center_city3,center_city4,center_city6],axis =0)
Gyeonggi = Gyeonggi.reset_index()
Gyeonggi= Gyeonggi.drop(['index'], axis=1)
Gyeonggi.to_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/이커머스 최종 data/Gyeonggi.csv', index=False)

In [ ]:
Gyeonggi = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/이커머스 최종 data/Gyeonggi.csv')
Gyeonggi['품목코드__1']= Gyeonggi['품목코드'].str[0]
Gyeonggi.to_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/이커머스 최종 data/Gyeonggi.csv', index=False)

In [ ]:
Gyeonggi['날짜'] = pd.to_datetime(Gyeonggi['날짜'], format='%Y-%m-%d', errors='raise')
Gyeonggi['주'] = Gyeonggi['날짜'].dt.week
Gyeonggi['주문시간'] = Gyeonggi['주문시간'].astype(int)

In [ ]:
gg = pd.DataFrame()
for i in Gyeonggi.groupby(['날짜'],as_index=False).count()['날짜']:
  gg[i] = Gyeonggi[Gyeonggi['날짜'] == i].groupby(['품목코드__1'], as_index=False).count()['날짜']

gg = gg.T
gg.columns=['품목코드_1','품목코드_2','품목코드_3','품목코드_4','품목코드_5','품목코드_6','품목코드_7']

index = []
for i in range(len(gg)):
  index.append(i)

gg.index = index
gg

     품목코드_1  품목코드_2  품목코드_3  품목코드_4  품목코드_5  품목코드_6  품목코드_7
0        20      93      59     537     228      27       5
1        13      70      48     645     676     118       7
2        23      65      39     841     446     271       9
3        21      96      63     557     500      32       8
4        15     175     122     799     600      23       5
..      ...     ...     ...     ...     ...     ...     ...
117      26     104      51     413    1012      33       3
118       1      36     139      67     612     876      58
119       1      60     152      63     526    1102      48
120       1      56     156      70     578     882      56
121       1      47     135      77     598     707      46

[122 rows x 7 columns]

In [ ]:
Gyeonggi_day = pd.DataFrame()

Gyeonggi_day['날짜'] = Gyeonggi.groupby(['날짜'],as_index=False).count()['날짜']
Gyeonggi_day['주'] = Gyeonggi_day['날짜'].dt.week
Gyeonggi_day['물류량'] = Gyeonggi.groupby(['날짜'],as_index=False).count()['수화인주소1,2']
Gyeonggi_day['품목코드_1'] = gg['품목코드_1']
Gyeonggi_day['품목코드_2'] = gg['품목코드_2']
Gyeonggi_day['품목코드_3'] = gg['품목코드_3']
Gyeonggi_day['품목코드_4'] = gg['품목코드_4']
Gyeonggi_day['품목코드_5'] = gg['품목코드_5']
Gyeonggi_day['품목코드_6'] = gg['품목코드_6']
Gyeonggi_day['품목코드_7'] = gg['품목코드_7']
Gyeonggi_day['품목금액평균'] = Gyeonggi.groupby(['날짜'],as_index=False).mean()['품목금액']
Gyeonggi_day['평균기온'] = Gyeonggi.groupby(['날짜'],as_index=False).mean()['평균기온']
Gyeonggi_day['강수량평균'] = Gyeonggi.groupby(['날짜'],as_index=False).mean()['강수량']

Gyeonggi_day
Gyeonggi_day.to_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/회귀분석용 data/Gyeonggi_day.csv',index=False)

In [ ]:
Gyeonggi_week = pd.DataFrame()

Gyeonggi_week['주'] = Gyeonggi.groupby(['주'],as_index=False).count()['주']
Gyeonggi_week['물류량'] = Gyeonggi.groupby(['주'],as_index=False).count()['품목금액']
Gyeonggi_week['품목코드_1'] = Gyeonggi_day.groupby(['주'],as_index=False).sum()['품목코드_1']
Gyeonggi_week['품목코드_2'] = Gyeonggi_day.groupby(['주'],as_index=False).sum()['품목코드_2']
Gyeonggi_week['품목코드_3'] = Gyeonggi_day.groupby(['주'],as_index=False).sum()['품목코드_3']
Gyeonggi_week['품목코드_4'] = Gyeonggi_day.groupby(['주'],as_index=False).sum()['품목코드_4']
Gyeonggi_week['품목코드_5'] = Gyeonggi_day.groupby(['주'],as_index=False).sum()['품목코드_5']
Gyeonggi_week['품목코드_6'] = Gyeonggi_day.groupby(['주'],as_index=False).sum()['품목코드_6']
Gyeonggi_week['품목코드_7'] = Gyeonggi_day.groupby(['주'],as_index=False).sum()['품목코드_7']
Gyeonggi_week['품목금액평균'] = Gyeonggi.groupby(['주'],as_index=False).mean()['품목금액']
Gyeonggi_week['평균기온'] = Gyeonggi.groupby(['주'],as_index=False).mean()['평균기온']
Gyeonggi_week['강수량평균'] = Gyeonggi.groupby(['주'],as_index=False).mean()['강수량']

Gyeonggi_week
Gyeonggi_week.to_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/회귀분석용 data/Gyeonggi_week.csv',index=False)

### 2.2.2. 경남 데이터셋 생성

In [ ]:
Gyeongnam = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/회귀분석용 data/under_city0.csv')
Gyeongnam = Gyeongnam.reset_index()
Gyeongnam = Gyeongnam.drop(['index'], axis=1)

Gyeongnam.to_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/이커머스 최종 data/Gyeongnam.csv', index=False)

In [ ]:
Gyeongnam = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/이커머스 최종 data/Gyeongnam.csv')
Gyeongnam
Gyeongnam['품목코드__1']= Gyeongnam['품목코드'].str[0]
Gyeongnam.to_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/이커머스 최종 data/Gyeongnam.csv', index=False)

gg = pd.DataFrame()
for i in Gyeongnam.groupby(['날짜'],as_index=False).count()['날짜']:
  gg[i] = Gyeongnam[Gyeongnam['날짜'] == i].groupby(['품목코드__1'], as_index=False).count()['날짜']


gg = gg.T
gg.columns=['품목코드_1','품목코드_2','품목코드_3','품목코드_4','품목코드_5','품목코드_6','품목코드_7']

index = []
for i in range(len(gg)):
  index.append(i)

gg.index = index
gg

     품목코드_1  품목코드_2  품목코드_3  품목코드_4  품목코드_5  품목코드_6  품목코드_7
0       2.0     8.0     8.0    93.0    41.0     9.0     1.0
1       1.0     9.0    12.0    71.0    70.0    19.0     3.0
2       6.0     5.0   130.0    65.0    38.0     1.0     NaN
3       1.0    11.0     7.0    98.0    69.0     2.0     2.0
4       2.0    19.0    13.0   114.0    73.0     2.0     NaN
..      ...     ...     ...     ...     ...     ...     ...
117     2.0    13.0     9.0    46.0   140.0     4.0     1.0
118     4.0    26.0     1.0    74.0    99.0    10.0     NaN
119    10.0    38.0     4.0    92.0   179.0    11.0     2.0
120     6.0    22.0     5.0    90.0   147.0    10.0     1.0
121     6.0    19.0    14.0    80.0    99.0     3.0     2.0

[122 rows x 7 columns]

In [ ]:
Gyeongnam['날짜'] = pd.to_datetime(Gyeongnam['날짜'], format='%Y-%m-%d', errors='raise')
Gyeongnam['주'] = Gyeongnam['날짜'].dt.week

In [ ]:
Gyeongnam_day = pd.DataFrame()

Gyeongnam_day['날짜'] = Gyeongnam.groupby(['날짜'],as_index=False).count()['날짜']
Gyeongnam_day['주'] = Gyeongnam_day['날짜'].dt.week
Gyeongnam_day['물류량'] = Gyeongnam.groupby(['날짜'],as_index=False).count()['품목금액']
Gyeongnam_day['품목코드_1'] = gg['품목코드_1']
Gyeongnam_day['품목코드_2'] = gg['품목코드_2']
Gyeongnam_day['품목코드_3'] = gg['품목코드_3']
Gyeongnam_day['품목코드_4'] = gg['품목코드_4']
Gyeongnam_day['품목코드_5'] = gg['품목코드_5']
Gyeongnam_day['품목코드_6'] = gg['품목코드_6']
Gyeongnam_day['품목코드_7'] = gg['품목코드_7']
Gyeongnam_day['품목금액평균'] = Gyeongnam.groupby(['날짜'],as_index=False).mean()['품목금액']
Gyeongnam_day['평균기온'] = Gyeongnam.groupby(['날짜'],as_index=False).mean()['평균기온']
Gyeongnam_day['강수량평균'] = Gyeongnam.groupby(['날짜'],as_index=False).mean()['강수량']

Gyeongnam_day
Gyeongnam_day.to_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/회귀분석용 data/Gyeongnam_day.csv',index=False)

In [ ]:
Gyeongnam_week = pd.DataFrame()

Gyeongnam_week['주'] = Gyeongnam.groupby(['주'],as_index=False).count()['주']
Gyeongnam_week['물류량'] = Gyeongnam.groupby(['주'],as_index=False).count()['품목금액']
Gyeongnam_week['품목코드_1'] = Gyeongnam_day.groupby(['주'],as_index=False).sum()['품목코드_1']
Gyeongnam_week['품목코드_2'] = Gyeongnam_day.groupby(['주'],as_index=False).sum()['품목코드_2']
Gyeongnam_week['품목코드_3'] = Gyeongnam_day.groupby(['주'],as_index=False).sum()['품목코드_3']
Gyeongnam_week['품목코드_4'] = Gyeongnam_day.groupby(['주'],as_index=False).sum()['품목코드_4']
Gyeongnam_week['품목코드_5'] = Gyeongnam_day.groupby(['주'],as_index=False).sum()['품목코드_5']
Gyeongnam_week['품목코드_6'] = Gyeongnam_day.groupby(['주'],as_index=False).sum()['품목코드_6']
Gyeongnam_week['품목코드_7'] = Gyeongnam_day.groupby(['주'],as_index=False).sum()['품목코드_7']
Gyeongnam_week['품목금액평균'] = Gyeongnam.groupby(['주'],as_index=False).mean()['품목금액']
Gyeongnam_week['평균기온'] = Gyeongnam.groupby(['주'],as_index=False).mean()['평균기온']
Gyeongnam_week['강수량평균'] = Gyeongnam.groupby(['주'],as_index=False).mean()['강수량']

Gyeongnam_week
Gyeongnam_week.to_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/회귀분석용 data/Gyeongnam_week.csv',index=False)

## 2.3 지역 데이터에 코로나, 휴일여부 결합

### 2.3.1 코로나,휴일 데이터

In [ ]:
corona = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/코로나 data/코로나_확진자_데이터.csv')
corona

def co_c(i):
  co_g = corona[corona['gubun'] == i]
  co_g = co_g.reset_index(drop=True)
  co_g['createDt'] = pd.to_datetime(co_g['createDt'], format='%Y-%m-%d', errors='raise')
  co_g['날짜'] = co_g['createDt']
  co_g['날짜'] = co_g['날짜'].astype('str')
  co_g['일일 코로나 확진자'] = co_g['incDec'] 
  co_g['주'] = co_g['createDt'].dt.week
  co_g = co_g.drop(['createDt','incDec'], axis=1)
  
  return co_g

In [ ]:
holiday = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/휴일 data/final_휴일_1.csv')
holiday
#holiday['날짜'] = pd.to_datetime(holiday['날짜'], format='%Y-%m-%d', errors='raise')

### 2.3.2. 경기도 + 코로나 + 휴일여부

In [ ]:
Gyeonggi= pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/이커머스 최종 data/Gyeonggi.csv')
Gyeonggi

In [ ]:
Gyeonggi_1 = pd.merge(Gyeonggi,co_c('경기'),on='날짜')
Gyeonggi_1 = pd.merge(Gyeonggi_1,holiday,how='outer',on='날짜')
Gyeonggi_1 = Gyeonggi_1.drop_duplicates()
Gyeonggi_1 = Gyeonggi_1.drop_duplicates()
Gyeonggi_1 = Gyeonggi_1.fillna('N')

Gyeonggi_1.to_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/회귀분석용 data/Gyeonggi_ch.csv',index=False)
Gyeonggi_1

In [ ]:
Gyeonggi_day = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/회귀분석용 data/Gyeonggi_day.csv')
Gyeonggi_day

In [ ]:
Gyeonggi_day_1 = pd.merge(Gyeonggi_day,co_c('경기'),on='날짜')
Gyeonggi_day_1 = pd.merge(Gyeonggi_day_1,holiday,how='outer',on='날짜')
Gyeonggi_day_1 = Gyeonggi_day_1.drop_duplicates()
Gyeonggi_day_1 = Gyeonggi_day_1.drop_duplicates()
Gyeonggi_day_1 = Gyeonggi_day_1.fillna('N')

Gyeonggi_day_1.to_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/회귀분석용 data/Gyeonggi_day_ch.csv',index=False)
Gyeonggi_day_1

In [ ]:
Gyeonggi_week = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/회귀분석용 data/Gyeonggi_week.csv')
Gyeonggi_week = pd.merge(Gyeonggi_week,co_c('경기').groupby(['주'],as_index=False).sum(),how='outer',on='주')
Gyeonggi_week
Gyeonggi_week.to_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/회귀분석용 data/Gyeonggi_week_ch.csv',index=False)

### 2.3.3. 경상남도 + 코로나 + 휴일여부

In [ ]:
Gyeongnam= pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/이커머스 최종 data/Gyeongnam.csv')
Gyeongnam

In [ ]:
Gyeongnam_1 = pd.merge(Gyeongnam,co_c('경남'),on='날짜')
Gyeongnam_1 = Gyeongnam_1.fillna(0)
Gyeongnam_1 = pd.merge(Gyeongnam_1,holiday,how='outer',on='날짜')
Gyeongnam_1 = Gyeongnam_1.drop_duplicates()
Gyeongnam_1 = Gyeongnam_1.fillna('N')
Gyeongnam_1

Gyeongnam_1.to_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/회귀분석용 data/Gyeongnam_ch.csv',index=False)

In [ ]:
Gyeongnam_day = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/회귀분석용 data/Gyeongnam_day.csv')
Gyeongnam_day

In [ ]:
Gyeongnam_day_1 = pd.merge(Gyeongnam_day,co_c('경남'),on='날짜')
Gyeongnam_day_1 = Gyeongnam_day_1.fillna(0)
Gyeongnam_day_1 = pd.merge(Gyeongnam_day_1,holiday,how='outer',on='날짜')
Gyeongnam_day_1 = Gyeongnam_day_1.drop_duplicates()
Gyeongnam_day_1 = Gyeongnam_day_1.fillna('N')
Gyeongnam_day_1

Gyeongnam_day_1.to_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/회귀분석용 data/Gyeongnam_day_ch.csv',index=False)

In [ ]:
Gyeongnam_week = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/회귀분석용 data/Gyeongnam_week.csv')
Gyeongnam_week = pd.merge(Gyeongnam_week,co_c('경남').groupby(['주'],as_index=False).sum(),how='outer',on='주')
Gyeongnam_week

Gyeongnam_week.to_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/회귀분석용 data/Gyeongnam_week_ch.csv',index=False)

## 2.4 도 데이터 시계열 확인 EDA

In [ ]:
def week_EDA(fc):
  fig = px.line(fc, x='주', y='물류량', title='주에 따른 물류량 EDA', text='물류량')
  return fig

In [ ]:
def day_EDA(fc):
  fig = px.line(fc, x='날짜', y='물류량', title='일에 따른 물류량 EDA', text='물류량')
  return fig

In [ ]:
Gyeonggi_week = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/이커머스 최종 data/Gyeonggi_week-1.csv')
week_EDA(Gyeonggi_week)

In [ ]:
Gyeongnam_week = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/이커머스 최종 data/Gyeongnam_week-1.csv')
week_EDA(Gyeongnam_week)

In [ ]:
Gyeonggi_day = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/이커머스 최종 data/gyeonggi_day_1.csv')
day_EDA(Gyeonggi_day)

In [ ]:
gyeongnam_day = pd.read_csv('/content/drive/Shareddrives/2021 CJ 대한통운 공모전/data/이커머스 최종 data/gyeonnam_day_1.csv')
day_EDA(gyeongnam_day)