### 한국관광데이터랩 데이터 전처리
- https://datalab.visitkorea.or.kr/datalab/portal/main/getMainForm.do
- 서울 경기 인천
    - 인기 관광지 (전체, 내지인, 외지인)
    - 내국인 관심 관광지
    - 외국인 관심 관광지 (영어, 일어, 중어)

In [1]:
import zipfile
import os
import glob

import pandas as pd
import numpy as np

In [2]:
list_zip = glob.glob('data/**.zip')
print(list_zip)

for i in list_zip:
    zipfile.ZipFile(i).extractall()

['data\\20230620232743_서울특별시_202206-202305_데이터랩_다운로드.zip', 'data\\20230621222252_서울특별시_202206-202305_데이터랩_다운로드.zip', 'data\\20230621222307_서울특별시_202206-202305_데이터랩_다운로드.zip', 'data\\20230621222337_경기도_202206-202305_데이터랩_다운로드.zip', 'data\\20230621222404_경기도_202206-202305_데이터랩_다운로드.zip', 'data\\20230621222415_경기도_202206-202305_데이터랩_다운로드.zip', 'data\\20230621222453_인천광역시_202206-202305_데이터랩_다운로드.zip', 'data\\20230621222508_인천광역시_202206-202305_데이터랩_다운로드.zip', 'data\\20230621222516_인천광역시_202206-202305_데이터랩_다운로드.zip', 'data\\20230623141303_서울특별시_202206-202305_데이터랩_다운로드.zip', 'data\\20230623141319_경기도_202206-202305_데이터랩_다운로드.zip', 'data\\20230623141339_인천광역시_202206-202305_데이터랩_다운로드.zip']

In [3]:
list_csv = glob.glob('**.csv')
print(list_csv)

['20230620232743_인기관광지_외지인.csv', '20230620232743_인기관광지_전체.csv', '20230620232743_인기관광지_현지인.csv', '20230621222252_내국인 관심 관광지.csv', '20230621222307_외국인 관심 관광지_영어권.csv', '20230621222307_외국인 관심 관광지_일본어.csv', '20230621222307_외국인 관심 관광지_중간체.csv', '20230621222307_외국인 관심 관광지_중번체.csv', '20230621222337_인기관광지_외지인.csv', '20230621222337_인기관광지_전체.csv', '20230621222337_인기관광지_현지인.csv', '20230621222404_내국인 관심 관광지.csv', '20230621222415_외국인 관심 관광지_영어권.csv', '20230621222415_외국인 관심 관광지_일본어.csv', '20230621222415_외국인 관심 관광지_중간체.csv', '20230621222415_외국인 관심 관광지_중번체.csv', '20230621222453_인기관광지_외지인.csv', '20230621222453_인기관광지_전체.csv', '20230621222453_인기관광지_현지인.csv', '20230621222508_내국인 관심 관광지.csv', '20230621222516_외국인 관심 관광지_영어권.csv', '20230621222516_외국인 관심 관광지_일본어.csv', '20230621222516_외국인 관심 관광지_중간체.csv', '20230621222516_외국인 관심 관광지_중번체.csv', '20230623141303_방문자 성연령별 분포.csv', '20230623141319_방문자 성연령별 분포.csv', '20230623141339_방문자 성연령별 분포.csv', '경기도_방문자 성연령별 분포.csv', '서울_방문자 성연령별 분포.csv', '인천_방문자 성연령별 분포.csv']

In [22]:
def mk_sido(data):
    add_list = []
    for i in range(len(data)):
        add_list.append(data['주소'][i][:2])
    data['시도'] = add_list
    return data

def mk_sort(data):
    data = data.sort_values(data.columns[4], ascending=False, ignore_index=True)
    return data

def mk_df(name, sido = True):
    df = pd.DataFrame()
    list_csv = glob.glob(name)
    for i in list_csv:
        data = pd.read_csv(i, encoding='cp949')
        df = pd.concat([df,data],axis=0, ignore_index=True)
        
    
    if sido == True:
        df = mk_sido(df)
        df = mk_sort(df)
        df.columns = ['순위','관광지명','주소','분류','검색수','시도']
       
    return df

In [23]:
pop_out = mk_df('*_인기관광지_외지인.csv')
pop_in = mk_df('*_인기관광지_현지인.csv')
pop_all = mk_df('*_인기관광지_전체.csv')

pop_local = mk_df('*_내국인 *.csv',sido=False)
pop_for = mk_df('*_외국인 *.csv',sido=False)

In [29]:
pop_out.head(5)

   순위           관광지명                      주소    분류      검색수  시도   종류
0   1  인천국제공항제1여객터미널         인천 중구 공항로 272-0  교통시설  2223643  인천  외지인
1   1         스타필드하남       경기 하남시 미사대로 750-0   쇼핑몰  1945622  경기  외지인
2   1      김포국제공항국내선        서울 강서구 하늘길 111-0  교통시설  1671746  서울  외지인
3   2  인천국제공항제2여객터미널     인천 중구 제2터미널대로 446-0  교통시설  1020780  인천  외지인
4   2           에버랜드  경기 용인시 처인구 에버랜드로 199-0  테마공원   915327  경기  외지인

In [28]:
pop_out['종류'] = '외지인'
pop_in['종류'] = '현지인'
pop_all['종류'] = '전체'

pop = pd.DataFrame()
pop = pd.concat([pop,pop_out,pop_in,pop_all],axis=0)
pop

      순위           관광지명                      주소       분류      검색수  시도   종류
0      1  인천국제공항제1여객터미널         인천 중구 공항로 272-0     교통시설  2223643  인천  외지인
1      1         스타필드하남       경기 하남시 미사대로 750-0      쇼핑몰  1945622  경기  외지인
2      1      김포국제공항국내선        서울 강서구 하늘길 111-0     교통시설  1671746  서울  외지인
3      2  인천국제공항제2여객터미널     인천 중구 제2터미널대로 446-0     교통시설  1020780  인천  외지인
4      2           에버랜드  경기 용인시 처인구 에버랜드로 199-0     테마공원   915327  경기  외지인
..   ...            ...                     ...      ...      ...  ..  ...
295   96         토지금고시장    인천 미추홀구 낙섬중로38번길 5-0       시장    40253  인천   전체
296   97         인천국제CC         인천 서구 도요지로 37-0  육상레저스포츠    40021  인천   전체
297   98       모다아울렛부평점       인천 부평구 부평문화로 35-0      쇼핑몰    39651  인천   전체
298   99        구읍뱃터어시장         인천 중구 은하수로 12-0       시장    38939  인천   전체
299  100           하늘정원                   인천 중구     도시공원    38853  인천   전체

[900 rows x 7 columns]

In [34]:
pop.to_csv('pop.csv',index=False)

pop_out.to_csv('pop_out.csv',index=False)
pop_in.to_csv('pop_in.csv',index=False)
pop_all.to_csv('pop_all.csv',index=False)
pop_local.to_csv('pop_local.csv',index=False)
pop_for.to_csv('pop_for.csv',index=False)

### end of script